### ISSUE TITLE
Remove "as of" field in stats detail view

### ISSUE THREAD

**Issue by thieflord06** [ClearskyApp06/ClearskyUI#102]
Maybe make it a greyed out placement somewhere, but NOT in the grid view.

**Comment by ian-pvd** [comment]
I am set up and ready to work on Clearsky. I plan on taking a look at this issue tomorrow.

**Comment by ian-pvd** [comment]
There is a PR for this issue that is ready to review here: https://github.com/ClearskyApp06/ClearskyUI/pull/181
