### ISSUE TITLE
Top blocklist results display issue & network circle

### ISSUE THREAD

**Issue by thieflord06** [ClearskyApp06/ClearskyUI#136]
On first load the top blocklists and network circle will populate briefly and then transition to the loading indication (waiting for the API to respond) and for the network circle it will default to the numbers in network-circle.js

The data being shown is from a cache that is on the web server that is pushed from the backend to:

"top_blocked": f"{push_server}/api/v1/base/reporting/stats-cache/top-blocked",
                "top_24_blocked": f"{push_server}/api/v1/base/reporting/stats-cache/top-24-blocked",
                "block_stats": f"{push_server}/api/v1/base/reporting/stats-cache/block-stats",
                "total_users": f"{push_server}/api/v1/base/reporting/stats-cache/total-users",

The workflow on this needs to be fixed and I don't think the implementation was fully fleshed out initially.

**Comment by noahm** [comment]
There may be more work to be done in managing how this data refreshes, but I think this particular issue is resolved with recent changes
