### ISSUE TITLE
Tooltip for a user has outsized large DID

### ISSUE THREAD

**Issue by mihailik** [ClearskyApp06/ClearskyUI#173]
**Describe the bug**
Tooltip can be helpful to avoid jumping through navigation.

But one of its downsides is the wild huge DID

<img width="365" alt="image" src="https://github.com/user-attachments/assets/3a2bf37f-012e-465a-a01a-ccfadb15da15">

**To Reproduce**
Mouse over any user.

**Expected behavior**
Show did in small font comparable to the bio.

**Comment by akash70629** [comment]
@noahm please assign me this issue.
