### ISSUE TITLE
Add hyperlink to list URL

### ISSUE THREAD

**Issue by thieflord06** [ClearskyApp06/ClearskyUI#186]
Add hyperlink to list name to be able to directly navigate to it.

![image](https://github.com/user-attachments/assets/8d4d4901-55e6-48f9-ad50-0fe95b3cd2fb)

**Comment by thieflord06** [comment]
Blocker: API needs to be updated with URL on the fly fix (in progress).

**Comment by seanmunson** [comment]
I can fix this...
