### ISSUE TITLE
Add placement in profile landing page

### ISSUE THREAD

**Issue by thieflord06** [ClearskyApp06/ClearskyUI#187]
Users have been requesting to see what 'place' they are on bluesky, some have also believed that they could get this info on clearsky already. This is now in place:

API: /api/v1/anon/placement/<client_identifier>

returns {"identity": string, "status": bool, "data": int || null}

Placement idea/guide:

desktop:
![image](https://github.com/user-attachments/assets/da2a5e85-b41f-421a-83ba-93563704836f)

mobile:
![image](https://github.com/user-attachments/assets/78391293-a55f-4d07-9ff9-8660876eb2f9)

**Comment by seanmunson** [comment]
I can help with this.
