### ISSUE TITLE
Rework block stats table view

### ISSUE THREAD

**Issue by thieflord06** [ClearskyApp06/ClearskyUI#195]
Remove Profile URL column in block stats column and make the handle columns hyperlinks that go to the profile URL

Also, separate into two tables. One for the overall stats and one for the top blocked stats so that the header columns are associated correctly with the data.

https://github.com/user-attachments/assets/c5b55cde-b843-41eb-a81f-58eac1e77296

![image](https://github.com/user-attachments/assets/dd008987-0082-47e2-aa9e-00b81221eaf6)

![image](https://github.com/user-attachments/assets/c144759e-2f18-4db7-aed7-d17b4536aadf)

**Comment by thieflord06** [comment]
@Macdonny you got it.

**Comment by Macdonny** [comment]
@thieflord06 opened a pull request for this.

PR: https://github.com/ClearskyApp06/ClearskyUI/pull/227

**Comment by thieflord06** [comment]
Fixed in: #227
