### ISSUE TITLE
Redirects for old URL needs to be re-added

### ISSUE THREAD

**Issue by thieflord06** [ClearskyApp06/ClearskyUI#201]
The old URL redirect was being handled in the python server, now that we are using a straight react server this needs to be added back.

Posts: 
https://bsky.app/profile/purplevoid.bsky.social/post/3kmloemo7k42t

https://bsky.app/profile/autiomaa.org/post/3kmfypkdksu2a

https://bsky.app/profile/autiomaa.org/post/3kmfts64zlo2f

old URL: https://bsky.thieflord.dev

needs to be redirected to: https://clearsky.app

**Comment by thieflord06** [comment]
@ian-pvd

**Comment by Prayag-09** [comment]
Hi @thieflord06 
Could you please assign this issue to me? I’d be happy to work on it and contribute.

**Comment by thieflord06** [comment]
301 redirect added in DNS.

**Comment by thieflord06** [comment]
Added DNS for path forwarding too, no need to add it in app anymore.
