### ISSUE TITLE
re-add privacy/terms&conditions

### ISSUE THREAD

**Issue by thieflord06** [ClearskyApp06/ClearskyUI#205]
I spoke with the lawyers and they said that we do need these things for compliance:

privacy policy
cookie policy
terms and conditions

commit: fecc976a is where it was removed.

**Comment by thieflord06** [comment]
If it's just a revert to old code I can do that myself, unless there is a more appropriate way to do it.

**Comment by noahm** [comment]
Compliance with what specifically? We don't set any cookies at all. Would a page that simply stated as much count as a cookie policy?

I don't want to just revert to the previous tool for several reasons. I think the legalese in these pages is bad and the popup prompt for consent is absolutely not necessary, even if the other policy and terms pages are.

**Comment by thieflord06** [comment]
I think we can leave out the cookie policy. I pushed the htmls because I was trying to get back into my open collective account. I agree that the pop up is a little much.

We can just add the links at the top like it was before.

**Comment by thieflord06** [comment]
Re-added in dev branch on 28037c8f2f53f48d39aeb1310d3e4ae2c7a7d258

This will with be pushed to main with the next PR merge or once I have finalized the wording in the documentation, whichever comes first.
