### ISSUE TITLE
List count load in sequence

### ISSUE THREAD

**Issue by thieflord06** [ClearskyApp06/ClearskyUI#222]
UI says "not a member of any lists" while it's waiting for the server to respond. "counting lists" is there and "not a member of any lists" needs to be hidden until there is a return.

ex: https://clearsky.app/bsky.app/lists
![image](https://github.com/user-attachments/assets/4c322350-8315-4f53-8a14-43b8568da59b)

**Comment by Macdonny** [comment]
I can work on this @thieflord06
