### ISSUE TITLE
Fix UI/UX for user not found

### ISSUE THREAD

**Issue by thieflord06** [ClearskyApp06/ClearskyUI#35]
UI needs to respond and show when a user doesn't exist (related to #184)

Or when incorrect URL is clicked:

This was shared from the old site (which is now redirecting to ClearSky.app)

Post: https://bsky.app/profile/purplevoid.bsky.social/post/3kmloemo7k42t

Ex: https://bsky.thieflord.dev/selection_handle

![Screenshot_20240229_221225_Chrome.jpg](https://github.com/thieflord06/ClearskyUI/assets/25804734/bae6a919-7acb-41bb-8518-884eefabb2b4)

**Comment by ian-pvd** [comment]
I am set up and ready to work on Clearsky. I plan on taking a look at this issue tomorrow.

**Comment by thieflord06** [comment]
@ian-pvd This issue is 2 in one. Which part are you working on:

adding redirect into react
fixing user not found issue

**Comment by thieflord06** [comment]
the hyperlink needs to be removed when an account isn't active.

![image](https://github.com/user-attachments/assets/2ff55e49-1278-4207-b7f6-988808ed5d02)

**Comment by thieflord06** [comment]
I made a separate issue for the second part of this @noahm fixed the other half in his recent PR.
