### ISSUE TITLE
Long handle in handle history causing UI issues. 

### ISSUE THREAD

**Issue by thieflord06** [ClearskyApp06/ClearskyUI#55]
I found something weird on Clearsky

I typed 'soap' into search to find this account:
![Screen_Shot_2024-03-13_at_21.30.16.png](https://github.com/thieflord06/ClearskyUI/assets/25804734/1689e2c9-eadc-4b2d-a606-07af0b6b1ca9)

but when I click it it leads me here: https://clearsky.app/soap.soap.soap.soap.soap.soap.soap.soap.soap.soap.soap.soap.soap.soap.soap.soap.soap.soap.soap.soap.soap.soap.soap.soap.soap.soap.soap.soap.soap.soap.soap.soap.soap.soap.soap.soap.soap.soap.soap.soap.soap.soap.soap.soap.soap.soap.soap.boytw.ink

(they change the handle often, so you probably have the older version saved)

it shows the long one first and then once more data loads via xhr it shows soap.systems, but I guess it doesn't update the href in the link

and then when I open that something very funny happens, there's a block count counting up to ~700 and then down to 0 again and then back up forever 😃

https://github.com/thieflord06/ClearskyUI/assets/25804734/6a3ec9ab-1dbc-48f7-b250-7463f6350d18

and if I manually try to open https://clearsky.app/soap.systems, instead the left sidebar goes full screen and the right sidebar with block list hides

**Comment by noahm** [comment]
Duplicates #180
Closing this one because I think the other one has a much clearer description and example profile to test with
